### ISSUE TITLE
Has issues streaming, but not preloading

### ISSUE THREAD

**Issue by m0ngr31** [VJAI/musquito#22]
When I try to do:

```js
const buzz = $buzz({
  src: 'https://myurl.com/my-song.mp3',
  stream: true,
  format: 'mp3',
});

buzz.play();
```

I'll get the following message in the console:

```
MediaElementAudioSource outputs zeroes due to CORS access restrictions for https://myurl.com/my-song.mp3
```

But when I set `stream` to false it loads fine.

I'm trying to replace Howler, and streaming works from it with the same URL, so I'm not sure what the issue is.

**Comment by VJAI** [comment]
I think you should set proper access control allow headers from server.

For example this url works "https://raw.githubusercontent.com/VJAI/musquito/master/sounds/bg.mp3" but not this one "http://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3" because the former one sends the "Access-Control-Allow-Origin" header in the response. Is it possible for you to set the CORS headers from server. Sorry for the delayed response.

**Comment by VJAI** [comment]
@m0ngr31 Any luck by setting access control headers? 

The problem is Howler uses plain Audio element for streaming but here we use MediaElementAudioSourceNode along with Audio element. The Web Audio API needs proper access control headers to be set to solve the CORS issues.

**Comment by m0ngr31** [comment]
So the project I built (https://github.com/m0ngr31/jellyamp) is too general purpose to have everyone running it change their CORS headers when Howler works okay already. There are just a few things I didn't like about it, but it'll work for now.
